export const Images = {
  1: require('../../../assets/images/questIcons/1.png'),
  2: require('../../../assets/images/questIcons/2.png'),
  3: require('../../../assets/images/questIcons/3.png'),
  4: require('../../../assets/images/questIcons/4.png'),
  5: require('../../../assets/images/questIcons/5.png'),
  6: require('../../../assets/images/questIcons/6.png'),
  7: require('../../../assets/images/questIcons/7.png'),
  8: require('../../../assets/images/questIcons/8.png'),
  9: require('../../../assets/images/questIcons/9.png'),
  10: require('../../../assets/images/questIcons/10.png'),
  11: require('../../../assets/images/questIcons/11.png'),
  12: require('../../../assets/images/questIcons/12.png'),
  13: require('../../../assets/images/questIcons/13.png'),
  14: require('../../../assets/images/questIcons/14.png'),
  15: require('../../../assets/images/questIcons/15.png'),
  16: require('../../../assets/images/questIcons/16.png'),
  17: require('../../../assets/images/questIcons/17.png'),
  18: require('../../../assets/images/questIcons/18.png'),
  19: require('../../../assets/images/questIcons/19.png'),
  20: require('../../../assets/images/questIcons/20.png'),
  21: require('../../../assets/images/questIcons/21.png'),
  22: require('../../../assets/images/questIcons/22.png'),
  23: require('../../../assets/images/questIcons/23.png'),
  24: require('../../../assets/images/questIcons/24.png'),
  25: require('../../../assets/images/questIcons/25.png'),
};
