export const LOAD_QUESTS_SUCCESS = 'LOAD_QUESTS_SUCCESS';
export const LOAD_QUEST_SUCCESS = 'LOAD_QUEST_SUCCESS'; 
export const LOAD_FEEDBACKS_SUCCESS = 'LOAD_FEEDBACKS_SUCCESS';
export const ADD_FEEDBACK_SUCCESS = 'ADD_FEEDBACK_SUCCESS';
export const ADD_FEEDBACK_ERROR = 'ADD_FEEDBACK_ERROR';
export const LOAD_STEPS_SUCCESS = 'LOAD_STEPS_SUCCESS';

/* -> Auth */
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';