export const LOAD_QUESTS_SUCCESS = 'LOAD_QUESTS_SUCCESS';
export const LOAD_PRIVATE_QUESTS_SUCCESS = 'LOAD_PRIVATE_QUESTS_SUCCESS';
export const LOAD_MY_QUESTS_SUCCESS = 'LOAD_MY_QUESTS_SUCCESS';
export const LOAD_QUEST_SUCCESS = 'LOAD_QUEST_SUCCESS'; 
export const LOAD_FEEDBACKS_SUCCESS = 'LOAD_FEEDBACKS_SUCCESS';
export const ADD_FEEDBACK_SUCCESS = 'ADD_FEEDBACK_SUCCESS';
export const ADD_FEEDBACK_ERROR = 'ADD_FEEDBACK_ERROR';
export const LOAD_STEPS_SUCCESS = 'LOAD_STEPS_SUCCESS';
export const DELETE_QUEST_SUCCESS = 'DELETE_QUEST_SUCCESS';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const EDIT_QUEST_SUCCESS = 'EDIT_QUEST_SUCCESS';
export const ADD_PROGRESS_SUCCESS = 'ADD_PROGRESS_SUCCESS';

/* -> Auth */
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const ADD_QUEST_SUCCESS = 'ADD_QUEST_SUCCESS';